<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.7</version>
        <relativePath/>
    </parent>
    
    <groupId>ru.grafit</groupId>
    <artifactId>recognition</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Recognition Microservices</name>
    <description>Microservices architecture for speech recognition service</description>
    
    <modules>
        <module>recognition-common</module>
        <module>recognition-api-gateway</module>
        <module>recognition-request-service</module>
        <module>recognition-processing-service</module>
        <module>recognition-result-service</module>
    </modules>
    
    <properties>
        <java.version>21.0.0</java.version>
        <protobuf.version>3.23.4</protobuf.version>
        <grpc.version>1.63.0</grpc.version>
        <kafka-clients.version>3.6.1</kafka-clients.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <protobuf-plugin.version>2.4.0</protobuf-plugin.version>
    </properties>
    
    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.30</version>
            </dependency>
            <dependency>
                <groupId>ru.grafit</groupId>
                <artifactId>recognition-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.springframework.data/spring-data-r2dbc -->
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-r2dbc</artifactId>
                <version>3.5.3</version>
            </dependency>

            <!-- Reactor Test -->
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-test</artifactId>
                <version>3.6.5</version>
                <scope>test</scope>
            </dependency>


            <!-- Другие версии зависимостей -->
            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-spring-boot3</artifactId>
                <version>2.1.0</version>
            </dependency>
            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-reactor</artifactId>
                <version>2.1.0</version>
            </dependency>
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>8.5.7</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>21</source>
                        <target>21</target>
                        <release>21</release>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>1.18.30</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
