server:
  port: 8082

spring:
  application:
    name: recognition-request-service
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/recognition}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: request-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

logging:
  level:
    ru.grafit.recognition.request: INFO

